Fix Binance Symbol To Currency Pair (#156)
* Fix build

Fix build.
Travis build error: https://travis-ci.org/bitrich-info/xchange-stream

[ERROR] /home/travis/build/bitrich-info/xchange-stream/xchange-hitbtc/src/main/java/info/bitrich/xchangestream/hitbtc/HitbtcStreamingExchange.java:[13,8] info.bitrich.xchangestream.hitbtc.HitbtcStreamingExchange is not abstract and does not override abstract method useCompressedMessages(boolean) in info.bitrich.xchangestream.core.StreamingExchange

* Upgrade XChange Version

* Fix wrong symbol to currency pair (e.g. BTC/USDT was transformed into btcusd instead of btcusdt)